### ISSUE TITLE
Python spits Errors when trying to run the runserver.sh script

### ISSUE THREAD

**Issue by AsherGlick** [Briefcase/Briefcase#18]
Here is an dump of the errors it output.
When trying to run syncdb it also spits out errors, though I am not sure if they are the same ones

```
Validating models...

Unhandled exception in thread started by <bound method Command.inner_run of <django.core.management.commands.runserver.Command object at 0x1dbad10>>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 91, in inner_run
    self.validate(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 266, in validate
    num_errors = get_validation_errors(s, app)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/validation.py", line 30, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 158, in get_app_errors
    self._populate()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 67, in _populate
    self.load_app(app_name)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 88, in load_app
    models = import_module('.models', app_name)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/vault/Code/projects/Briefcase/briefcase/briefcase/core/spreadsheet/models.py", line 10, in <module>
    core.module.register("Spreadsheet", "briefcase.core.spreadsheet.views.new")
  File "/home/vault/Code/projects/Briefcase/briefcase/briefcase/core/register.py", line 21, in register
    DocumentType(name=name, new_module=module).save()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 551, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 203, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1576, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 910, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 40, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.DatabaseError: no such table: core_documenttype
```

**Comment by akarnani** [comment]
This is a bug I am working on.  It is caused by briefcase/core/register.py line 11 (DocumentType.objects.all().delete()).  Comment out this line while running syncdb and then uncomment it to runserver.  Will create a fix ASAP.

**Comment by AsherGlick** [comment]
I have commented out just the `DocumentType.objects.all().delete()` function on line 11. That did not work. 

``` Python
def __init__(self):
    try:
        #DocumentType.objects.all().delete()
        pass

    except(DatabaseError):
        pass
```

Then i tried to comment out the whole function 

``` Python
def __init__(self):
    pass
    #try:
        #DocumentType.objects.all().delete()

    #except(DatabaseError):
        #pass
```

This is the errors produced when running `configure_database.sh`

```
$ ./configure_database.sh 
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 231, in execute
    self.validate()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 266, in validate
    num_errors = get_validation_errors(s, app)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/validation.py", line 30, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 158, in get_app_errors
    self._populate()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 67, in _populate
    self.load_app(app_name)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 88, in load_app
    models = import_module('.models', app_name)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/elhim/Code/projects/Briefcase/briefcase/briefcase/core/spreadsheet/models.py", line 10, in <module>
    core.module.register("Spreadsheet", "briefcase.core.spreadsheet.views.new")
  File "/home/elhim/Code/projects/Briefcase/briefcase/briefcase/core/register.py", line 22, in register
    DocumentType(name=name, new_module=module).save()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 551, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 203, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1576, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 910, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 40, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.DatabaseError: no such table: core_documenttype

```

**Comment by AsherGlick** [comment]
As a temporary fix i have commented out line `10` in `briefcase/briefcase/core/spreadsheet/models.py`

``` Python
core.module.register("Spreadsheet", "briefcase.core.spreadsheet.views.new")
```

This line did not necessarily need to be commented out but it appeared to be the root of the call that caused the error

The errors seemed to have arisen from `briefcase/core/register.py` line `22`

``` Python
DocumentType(name=name, new_module=module).save()
```

**Comment by AsherGlick** [comment]
Maybe that was not the best idea, I can now no longer log in or get to the login page, or access anything that requires me to be logged in. I can however log in via `/admin` and then the `user_profile` page and the spreadsheet will load just fine.

**Comment by AsherGlick** [comment]
I lied, the spreadsheet does not work, the static files seem to all 404. I will not be pushing any of the changes I made and I will leave the fixing to you. Hopefully this will get done soon.
